### ISSUE TITLE
Onyx submitted to clojars should be AOT'd

### ISSUE THREAD

**Issue by lbradstreet** [MichaelDrogalis/onyx#111]
@cmdrdats investigated why it takes so long to require onyx in a project. It turns out AOT compiling the version that is submitted to clojars cuts down the require time greatly.

**Comment by MichaelDrogalis** [comment]
Is this in conflict with x/blob/0.5.x/doc/user-guide/what-does-it-offer.md#aot-nothing ?

I don't want to lock anyone into a specific version of Clojure.

**Comment by lbradstreet** [comment]
You make a great point. I was trying to think of a catch and you found it.

I'll have to think about that one some more, but I think everyone will just have to get used to using tools.namespace.repl/refresh rather than restarting their repl.

**Comment by MichaelDrogalis** [comment]
Perhaps we can release an AOT'ed version that is lock-stepped with the same version.

**Comment by lbradstreet** [comment]
I don't think it's that big of a deal any more. Close for now?

**Comment by MichaelDrogalis** [comment]
I'll note in the docs about how to AOT it yourself if you want faster boot up times. Will close after I write it down.
