### ISSUE TITLE
Use Schema validation on peer and env config

### ISSUE THREAD

**Issue by MichaelDrogalis** [MichaelDrogalis/onyx#113]
A small thing to do to be a bit more user friendly.

**Comment by MichaelDrogalis** [comment]
Given the flexibility of what can be inside these maps - using Schema would close off the allowed values, even if we used `optional-key`. I'll pass on this change.

**Comment by lbradstreet** [comment]
We could just do a select keys on the map before doing the schema check on it. I'm happy to take this one.

**Comment by lbradstreet** [comment]
I'll also attempt to make them loose by default where there's any ambiguity about value types.

**Comment by MichaelDrogalis** [comment]
Okay, that sounds fine to me.
