### ISSUE TITLE
Increase default size of rotated logs

### ISSUE THREAD

**Issue by lbradstreet** [MichaelDrogalis/onyx#117]
I think this one was lost in a merge too

**Comment by MichaelDrogalis** [comment]
I really suck at merging. I did it a finite amount of times, though. Perhaps we can scan merge commits and look for my derps.

**Comment by MichaelDrogalis** [comment]
0.6, 0.5, and 0.4 seem to match: https://github.com/MichaelDrogalis/onyx/blob/0.5.x/src/onyx/logging_configuration.clj#L22

Can you recall where this change happened?

**Comment by lbradstreet** [comment]
I'll see if I can track it down. It's definitely possible I'm remembering it incorrectly.
