### ISSUE TITLE
Monitoring dashboard

### ISSUE THREAD

**Issue by MichaelDrogalis** [MichaelDrogalis/onyx#12]
This issue serves as a placeholder for the creation of another repository - onyx-dashboard. This dashboard will serve as a point of monitoring the status of what's happening inside Onyx by querying ZooKeeper. The data in ZooKeeper is immutable, and compressed with Fressian.

**Comment by MichaelDrogalis** [comment]
I'm interested in getting this out with the 0.5.0 release. Adding as a blocker.

**Comment by vijaykiran** [comment]
Sorry - my vacation turned out to be a "real" one so didn't get time at all. I'd dig into the 0.5.x changes this week to see if/how I can contribute.

**Comment by MichaelDrogalis** [comment]
No problem! Glad you got some rest in. :)

**Comment by MichaelDrogalis** [comment]
Repo at https://github.com/vijaykiran/onyx-dashboard

**Comment by MichaelDrogalis** [comment]
@vijaykiran 0.5.0 issues are going down faster than expected. I think we're gonna move forward without the dashboard for this release.

**Comment by lbradstreet** [comment]
@vijaykiran Since I haven't seen any movement I've created a new repo at https://github.com/lbradstreet/onyx-dashboard and add you as a contributor. Feel free to join in.

**Comment by MichaelDrogalis** [comment]
Done. :)
