### ISSUE TITLE
Peer makes a new link for each message type

### ISSUE THREAD

**Issue by lbradstreet** [MichaelDrogalis/onyx#122]
i.e. a new separate connection for ack, message sending, and completion messages

**Comment by MichaelDrogalis** [comment]
Let's take this a step further and use this issue to share a common link across all peers in a group. One idea I had is to modify the Component structure to launch a "PeerGroup". The System has a Component that launches N peers, and that Component obtains its dependencies from the shared group component.

**Comment by lbradstreet** [comment]
A separate peer-link is no longer created for each peer message type. 

Todo: 
[  ] establish peer link before task-lifecycle
[  ] peer group component
