### ISSUE TITLE
Make messaging implementation more on-demand

### ISSUE THREAD

**Issue by lbradstreet** [MichaelDrogalis/onyx#125]
If we're going to provide a netty option, then it should be usable without aeron being loaded at all.

**Comment by MichaelDrogalis** [comment]
We could provide two builds of Onyx with each release - a Netty version, and an Aeron version. This would keep the dependencies out entirely of the project if they aren't needed.

**Comment by MichaelDrogalis** [comment]
I'm not a big fan of this idea though, as it's operationally complex.

**Comment by lbradstreet** [comment]
I'm not a fan of that approach either. I think there better ways around the issue. I'll comment on them when I get a chance.

**Comment by MichaelDrogalis** [comment]
Do you think it's a reasonable goal to try and keep Aeron off the classpath altogether when it's not wanted? That has the advantage of not needing Java 8 - which may be a real concern.

**Comment by lbradstreet** [comment]
I think if we just make sure the ns using the Aeron / Netty classes are only required when the user decides to use it, then everything will work fine with java 7. 

Users can then also decide whether to exclude the dependencies if they wish.

**Comment by MichaelDrogalis** [comment]
If that works as described, that would be terrific. I suppose the thing to do would be to move the `require` into the function that initializes an Aeron component? As awkward as that is, it's exactly what we want.

**Comment by lbradstreet** [comment]
Exactly what I was thinking, and I'm quite certain it'll work. I'm happy to give this one a go.

It's a little awkward but no more than what we're doing when resolving functions in catalogs anyway :)

**Comment by MichaelDrogalis** [comment]
I'm absolutely fine with doing this. It's just a small, funny piece of Clojure that offers a huge win to the user. :)
