### ISSUE TITLE
Experiment with protocols instead of multimethods for lifecycles

### ISSUE THREAD

**Issue by MichaelDrogalis** [MichaelDrogalis/onyx#127]
Need to see what this is going to look like since it's a hot path.

**Comment by lbradstreet** [comment]
Definitely worth looking into. With 1.7 it's the least of our performance problems. That said, it might be worth making the change sooner rather than later, as it'll be less painful for users later on.

**Comment by MichaelDrogalis** [comment]
Yes, agreed - especially since it will affect plugin authors.

**Comment by lbradstreet** [comment]
I think we may want to look into reifying protocols using the new data driven functions. This may help for performance. If not I think we can close this one.

**Comment by MichaelDrogalis** [comment]
Agreed, I'm good to close.
