### ISSUE TITLE
Implement a core.async messaging implementation

### ISSUE THREAD

**Issue by lbradstreet** [MichaelDrogalis/onyx#145]
This would be the fastest implementation for single machine use and might provide a path forward for avoiding serialisation and network communication completely when local vpeers are communicating.

**Comment by MichaelDrogalis** [comment]
Tried to do this in between talks. WIP, but very close to complete: https://github.com/MichaelDrogalis/onyx/tree/core-async-messaging

**Comment by MichaelDrogalis** [comment]
Done.
