### ISSUE TITLE
Reduce protocol messages size by sending completion-id once per batch

### ISSUE THREAD

**Issue by lbradstreet** [MichaelDrogalis/onyx#148]
completion-id should be fixed over a batch of messages (sent from a particular peer with a fixed id). We should not be including this with every message, rather we should be only sending the completion-id once per batch and adding to the messages on the other side.

@MichaelDrogalis to confirm that my understanding is correct

**Comment by MichaelDrogalis** [comment]
Hm, what if a task has two inputs? It will have messages from both streams, with different completion-ids.

**Comment by lbradstreet** [comment]
Ah yes, I think I had this thought once before and I knew there was a catch I'd forgotten about. 

We can close this now then.
