### ISSUE TITLE
Task-level activity metrics

### ISSUE THREAD

**Issue by MichaelDrogalis** [MichaelDrogalis/onyx#153]
After talking with Zach Tellman, he pretty much convinced me that Onyx wouldn't be operationally usable if there isn't some way to tell how many segments/second each peer is processing. We can do this with Grafana, but I think I have a better design in mind. I'll update with details later.

**Comment by lbradstreet** [comment]
Haha, excellent. I've been feeling this way for a while and watching that talk really made me think the same.

**Comment by MichaelDrogalis** [comment]
#166 covers the rest of this.
