### ISSUE TITLE
Log and replica garbage collection

### ISSUE THREAD

**Issue by MichaelDrogalis** [MichaelDrogalis/onyx#64]
The log and replica can grow indefinitely. Needs a GC algorithm for both.

**Comment by MichaelDrogalis** [comment]
Done in 0.5.x. New `gc` API call.

**Comment by lbradstreet** [comment]
Cool. I was wondering about whether this could be an issue.

**Comment by MichaelDrogalis** [comment]
I think in practice, gc will be invoked very infrequently. The total number of messages that comprise the log for a streaming job is small, and even period batch jobs don't add too much to the disk space in ZK. If memory becomes a problem for the replica size, we can implement an interface to store it on disk. Cross that bridge when we come to it though.
