### ISSUE TITLE
0.5.0 release prep

### ISSUE THREAD

**Issue by MichaelDrogalis** [MichaelDrogalis/onyx#70]
There are just a few remaining things to do before the 0.5.0 release. Using this issue to track the small things:

- [x] #54 
- [x] #69
- [x] Update all plugins to 0.5.0-SNAPSHOT and run their test suites
- [x] Update/write documentation for the new coordination mechanisms
- [x] Update all examples
- [x] Make sure all the tests use the new APIs
- [x] Add example output for log subscriber
- [x] Update starter guide
- [x] Update lib-onyx
- [x] Reread the entire user guide to look for errors
- [x] Redeploy API docs to gh-pages
- [x] Write the blog post
- [x] Test 0.5.0 release candidate against Oxide
- [x] Release Onyx core 0.5.0 to Clojars
- [x] Release all plugins 0.5.0 to Clojars
- [x] Forward port documentation fixes from 0.4.x e.g. https://github.com/MichaelDrogalis/onyx/blob/0.5.x/doc/user-guide/peer-config.md#jgroups-configuration (lbradstreet happy to do this).

**Comment by MichaelDrogalis** [comment]
@lbradstreet Last one should be done in `70c30ae96ed857b7c8796334e6929a86c72cba57`. I merged 0.4.x -> master -> 0.5.x. I dont think I missed any, most of it merged cleanly.

**Comment by MichaelDrogalis** [comment]
Merged 0.5.x -> master:

159 files changed, 7942 insertions(+), 6051 deletions(-)

Ha.

**Comment by MichaelDrogalis** [comment]
Onyx 0.5.0 sits at comfortable 3664 lines. Onyx 0.4.1 was 4401. We went *down* in total lines of code and added tons of new functionality. Wild.

**Comment by lbradstreet** [comment]
Pretty good sign of a good design!

**Comment by MichaelDrogalis** [comment]
Everything's uploaded to Clojars. We'll make some serious noise in the morning. :D
