### ISSUE TITLE
Document use of HornetQ standalone mode

### ISSUE THREAD

**Issue by lbradstreet** [MichaelDrogalis/onyx#71]
See https://github.com/MichaelDrogalis/onyx/blob/0.5.x/doc/user-guide/peer-config.md#hornetqmode 
look at https://github.com/MichaelDrogalis/onyx/blob/96da8e96c9a9fd513238481fe72f2f8b73a65a84/test/onyx/hornetq/standalone_test.clj for example.

**Comment by MichaelDrogalis** [comment]
Thanks! Will tuck this one in before the release.

**Comment by MichaelDrogalis** [comment]
Fixed.
