### ISSUE TITLE
Remove all references to onyx/consumption

### ISSUE THREAD

**Issue by MichaelDrogalis** [MichaelDrogalis/onyx#74]
We're getting rid of sequential, so concurrent is the only option.

**Comment by CmdrDats** [comment]
I'm just curious - wasn't sequential a useful construct? Won't this break implementations that are expecting sequential consumption?

**Comment by MichaelDrogalis** [comment]
@CmdrDats Less useful than anticipated. It's been more helpful to set `:onyx/max-peers` to 1 and read the load in any order. Throughput really sucks if you need to have strict ordering, and it's very complicated to implement. Also, for `:sequential` to be useful, it has to be used in every task - merely one task that uses `:concurrent` will throw the ordering off.

I'm also not particularly worried about breaking backwards yet, though I try not to do anything drastic. Onyx isn't widely adopted yet.

**Comment by CmdrDats** [comment]
Cool :) makes sense - if you need to go sequential, you're probably in the wrong boat...

**Comment by MichaelDrogalis** [comment]
Sometimes it's useful for looking at a pre-sorted data set, but making Onyx have full batch and streaming capabilities in both directions is really hard. That said, when I start tearing things out, I'll see how hard it would be to keep it.

**Comment by MichaelDrogalis** [comment]
Done in `0.6.x`.
