### ISSUE TITLE
Use Nippy instead of Fressian

### ISSUE THREAD

**Issue by MichaelDrogalis** [MichaelDrogalis/onyx#90]
Nippy is benchmarking faster, and won't collide with Datomic.

**Comment by lbradstreet** [comment]
This should be a pretty easy switch in. 

When we do it, I'd like to make sure that custom types can be handled, and that encryption/compression can be easily configured. Shouldn't be too hard, but we will need to think about the correct place to do so.

https://github.com/ptaoussanis/nippy#custom-types-v21

**Comment by MichaelDrogalis** [comment]
Nippy has been switched in. Opening up a new issue for configurable compression properties, and configurable compression formats in general. See #96.
