### ISSUE TITLE
Job is not properly killed on peer crashes

### ISSUE THREAD

**Issue by lbradstreet** [MichaelDrogalis/onyx#92]
This may be related to HornetQ (see the peer log). Encountered with 0.5.2.

https://gist.githubusercontent.com/lbradstreet/230a2862627c03e55607/raw/onyx_log-cycling-peers.txt

Log entries:

https://gist.githubusercontent.com/lbradstreet/c1721d7d998d2ffea931/raw/dd3d7f1b9aa86059b5cc352426394f3a545c43b4/dumped_log.edn

**Comment by MichaelDrogalis** [comment]
Closing - dropped along with HornetQ.
