### ISSUE TITLE
Bootstrapping should return a lazy seq or generator function

### ISSUE THREAD

**Issue by MichaelDrogalis** [MichaelDrogalis/onyx#98]
This let's us get around the scaling problem with bootstrapping.

**Comment by MichaelDrogalis** [comment]
@lbradstreet @robert-stuttaford  I think we can scoot around this nicely by treating the output of a bootstrapped `apply-fn` as a lazy sequence that's never fully realized. When we write to output, we do some sort of `take-while` or `partition` business to write chunks to the output storage, and only stop when we hit `nil`. A bigger win is having input plugins that generate infinite sequences as first class citizens, which is what we're doing for benchmarking now. Thoughts?

**Comment by robert-stuttaford** [comment]
That sounds ideal to me! +1!

**Comment by lbradstreet** [comment]
Agreed. I think this makes a lot of sense for bootstrapping. If we need to write something more low level we can write a non-bootstrapped version. 

Are we going to give up on bootstrapping for streaming input plugins? I guess users can always use lazy-seq but it might be trickier than the alternative. Even if so, I think it's a reasonable trade off, and you can always write a non-bootstrapped version. 

Lucas

**Comment by MichaelDrogalis** [comment]
What about a bootstrapped version for streaming that generates an infinite seq? Do you see problems arising?

**Comment by MichaelDrogalis** [comment]
I'll pick this one up in the next 1-2 days.

**Comment by MichaelDrogalis** [comment]
Okay, here's a brain dump of some notes. Might not make a whole lot of sense, but I don't want to lose them.

There are two cases that we're trying to deal with here. First, the bootstrapping feature as is. Second, the Datomic plugin (reading a long sequence/generator).

Strategy for dealing with bootstrapping...

- The goal is to have a function that takes one value and returns a sequence of values. This sequence should be bounded, but should be chunked as its written out. The chunks ALSO need to hit storage, ZooKeeper in our case. This handles fault tolerance.
- It's easier to consider the MySQL case than the Datomic case. Datomic will probably end up being its own beast entirely.

- MySQL: All we need to get going is to be pointed at the table. From there, we count the number of rows. The chunks we write out are partition ranges. Each of these ranges needs to drop to ZooKeeper. The range sequence needs to be written out with proper batching. This is easy since we can already do this. We assume the sequence is relatively small and bounded.

- Here's where the Datomic case gets complicated - we don't necessarily want to hold the entire sequence in memory all at the same time.
- What do we do for big seqs? Obviously these need to pay the price of dropping a range to ZooKeeper. But how about buffering?

- Here's an idea: Create the sequence in the creation of the lifecycle resources. Mark the initial index as 0.
- The injection starts a thread that puts index ranges onto a channel. The channel helps provide some backpressure so that it doesn't produce too quickly.
- Now - how does the lifecycle keep moving? It reads off the channel itself!

- To summarize:
  - We start a task that uses a channel to communicate to the peer what to do.
  - The peer reads off the of the channel in the read phase. This makes the task backpressure accordingly.
  - The channel is filled with datoms from d/datoms from a thread on the injection
  - At the end of d/datoms, we plop a :done on the channel so that the peer knows it's all finished
  - This thread marks ranges as it reads, stuffing the index range into ZooKeeper along with its latest offset.
  - As segments are completed, we either mark the data as complete in ZooKeeper or blow it away.
  - This approaches bounds the input task to a single peer.
  - The result is that d/datoms is read from a single peer in a fault tolerant way, and scales out with the number of peers processing downstream. The fast\
er you can burn through the d/datoms index, the faster you can process the data.

**Comment by MichaelDrogalis** [comment]
Done -- moved functionality into plugins.
